// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD5bTzfNJyaei2jJObJadMTf8y8c0vDLA',
    appId: '1:17527570531:web:9e76ffbb949be2c3087856',
    messagingSenderId: '17527570531',
    projectId: 'planet-hero-202db',
    authDomain: 'planet-hero-202db.firebaseapp.com',
    storageBucket: 'planet-hero-202db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXV-4AtWXS1H0QAO_qCXS3c3AK0tb3LwQ',
    appId: '1:17527570531:android:5ba8f3bfc1f2046f087856',
    messagingSenderId: '17527570531',
    projectId: 'planet-hero-202db',
    storageBucket: 'planet-hero-202db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiZSRDyAcVRzMK2fZS7ZVjjxURw-FUyPU',
    appId: '1:17527570531:ios:60025919fff62145087856',
    messagingSenderId: '17527570531',
    projectId: 'planet-hero-202db',
    storageBucket: 'planet-hero-202db.appspot.com',
    iosClientId: '17527570531-nrnbiqfis235bdpj3v0kta3jln4uahch.apps.googleusercontent.com',
    iosBundleId: 'com.example.planetheroApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiZSRDyAcVRzMK2fZS7ZVjjxURw-FUyPU',
    appId: '1:17527570531:ios:60025919fff62145087856',
    messagingSenderId: '17527570531',
    projectId: 'planet-hero-202db',
    storageBucket: 'planet-hero-202db.appspot.com',
    iosClientId: '17527570531-nrnbiqfis235bdpj3v0kta3jln4uahch.apps.googleusercontent.com',
    iosBundleId: 'com.example.planetheroApplication',
  );
}
